### ISSUE TITLE
Is it possible to use ThemeManager without auto saving?

### ISSUE THREAD

**Issue by otomad** [WinUICommunity/Common#3]
I want to retrieve/save the settings by myself.

And it will automatically generates a folder in `%APPDATA%` that I want to store in another directory.

**Comment by ghost1372** [comment]
> I want to retrieve/save the settings by myself.
> 
> And it will automatically generates a folder in `%APPDATA%` that I want to store in another directory.

It is a very good suggestion, I will definitely add it.

**Comment by ghost1372** [comment]
@otomad 
I Added 2 new Property in ThemeOptions:

1.if you want to use your custom save and reload methods, you can turn off our BuiltIn Save and Loader:

```
// Default is: true
UseBuiltInConfig = false
```

2.if you want just to change save/reload location, you can set your custom location:

`BuiltInConfigFileName = "D:\newfolder\myfile.json"`

I am not sure about the naming of these 2 properties and I will probably change them.
Thank you for your good suggestion
